# Generated by Django 3.1.6 on 2021-02-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210203_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Дайте короткое название группе', max_length=200, verbose_name='группа/сообщество')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
